// Package compat guards the public API of the module across releases.
package compat

import (
	_ "embed"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// surfaceV2 is a consumer program that uses every exported identifier the
// public packages had at v2.16.1 (db12167): each function and method with its
// exact signature, each typed constant and variable, and each exported struct
// field with its exact type. It is generated by ./gen, never hand-edited, and
// deliberately excludes package api — the integration-test harness that was
// moved to internal/ because it drives admin-only routes (audit A-12).
//
//go:embed testdata/surface_v2.go.txt
var surfaceV2 []byte

func repoRoot(t *testing.T) string {
	t.Helper()

	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}

	return filepath.Clean(filepath.Join(wd, "..", ".."))
}

func goCmd(t *testing.T, dir string, args ...string) (string, error) {
	t.Helper()

	cmd := exec.Command("go", args...)
	cmd.Dir = dir
	// -mod=mod + GOPROXY=off: resolve the replace'd module and its
	// requirements from the local module cache only — no network.
	cmd.Env = append(os.Environ(), "GOFLAGS=-mod=mod", "GOPROXY=off", "GOWORK=off", "GOTOOLCHAIN=local")

	out, err := cmd.CombinedOutput()

	return string(out), err
}

// TestPreviousPublicSurfaceStillCompiles builds, in a throwaway module that
// depends on this checkout, a program using every previously exported symbol.
// A removed, renamed or re-typed export fails the build. Ringboost's producer
// and the e2e runner import this SDK, so this is the guard against breaking
// them in a minor release.
func TestPreviousPublicSurfaceStillCompiles(t *testing.T) {
	root := repoRoot(t)
	work := t.TempDir()

	goMod := "module compatcheck\n\ngo 1.25\n\nrequire github.com/helix-tools/sdk-go/v2 v2.0.0\n\nreplace github.com/helix-tools/sdk-go/v2 => " + root + "\n"
	if err := os.WriteFile(filepath.Join(work, "go.mod"), []byte(goMod), 0o644); err != nil {
		t.Fatal(err)
	}

	sum, err := os.ReadFile(filepath.Join(root, "go.sum"))
	if err != nil {
		t.Fatal(err)
	}

	if err := os.WriteFile(filepath.Join(work, "go.sum"), sum, 0o644); err != nil {
		t.Fatal(err)
	}

	if err := os.WriteFile(filepath.Join(work, "main.go"), surfaceV2, 0o644); err != nil {
		t.Fatal(err)
	}

	if out, err := goCmd(t, work, "build", "./..."); err != nil {
		t.Fatalf("a consumer of the previous public API no longer compiles — an exported symbol was removed, renamed or re-typed:\n%s", out)
	}
}

// TestPublicPackagesAreLibraryClean pins the A-12 outcome: no public package
// imports "testing" from non-test code, and nothing importable is named api
// (the admin-route test harness lives under internal/).
func TestPublicPackagesAreLibraryClean(t *testing.T) {
	root := repoRoot(t)

	out, err := goCmd(t, root, "list", "-f", "{{.ImportPath}} {{join .Imports \" \"}}", "./...")
	if err != nil {
		t.Fatalf("go list: %v\n%s", err, out)
	}

	const module = "github.com/helix-tools/sdk-go/v2"

	var public int

	for _, line := range strings.Split(strings.TrimSpace(out), "\n") {
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}

		pkg, imports := fields[0], fields[1:]
		rel := strings.TrimPrefix(strings.TrimPrefix(pkg, module), "/")

		if rel == "test" || strings.Contains(rel, "internal") {
			continue
		}

		public++

		if rel == "api" {
			t.Errorf("package %s is importable again: the admin-route harness must stay under internal/", pkg)
		}

		for _, imp := range imports {
			if imp == "testing" {
				t.Errorf("public package %s imports testing from non-test code", pkg)
			}
		}
	}

	if public == 0 {
		t.Fatal("found no public packages; the check itself is broken")
	}
}
